'use client';
import { useEffect, useRef, useState, type CSSProperties, type ReactNode } from 'react';
import { ArrowDown, ArrowRight, ArrowUpRight, Check, ChevronDown, Home, Utensils, ShoppingBag, Car, Smartphone, ShieldCheck, Download, X, Expand, Menu, ChartNoAxesColumnIncreasing } from 'lucide-react';
import { VisitorTracker } from './VisitorTracker';
import { CheckoutSection } from './CheckoutSection';
import { calculateSavings, carryForward, dateKey, EXPENSES, inr, storyBalance } from '@/lib/savingsDemo';

const asset = '/images/savings/';
const products = [
  { title: 'Printable Savings Challenges', file: 'challenges', purpose: 'A little motivation. A visible milestone.', detail: '12 ready-made goals, from 100 to 100,000. Pick your currency, print the pages you want, and mark each step.', kind: '01 / THE MOTIVATION' },
  { title: 'Smart Excel Savings Tracker', file: 'dashboard', purpose: 'Your goal, made into a daily plan.', detail: 'Set your target and dates. Record what you actually save. See the remaining amount, carry-forward and progress in one place.', kind: '02 / THE PLAN' },
  { title: 'Step-by-Step User Guide', file: 'guide', purpose: 'Clarity from the very first entry.', detail: 'From setting up your goal to recording partial savings, the guide walks you through the real tracker.', kind: '03 / THE GUIDANCE' },
];
function Marker({ children }: { children: ReactNode }) { return <p className="eyebrow">{children}</p>; }
function useSceneProgress() {
  const ref = useRef<HTMLElement>(null);
  const [progress, setProgress] = useState(0);
  useEffect(() => {
    const media = window.matchMedia('(prefers-reduced-motion: reduce)');
    let frame = 0;
    const update = () => { frame = 0; if (!ref.current) return; const rect = ref.current.getBoundingClientRect(); setProgress(media.matches ? 1 : Math.min(1, Math.max(0, -rect.top / Math.max(1, rect.height - window.innerHeight)))); };
    const schedule = () => { if (!frame) frame = requestAnimationFrame(update); };
    update(); window.addEventListener('scroll', schedule, { passive: true }); window.addEventListener('resize', schedule); media.addEventListener('change', schedule);
    return () => { cancelAnimationFrame(frame); window.removeEventListener('scroll', schedule); window.removeEventListener('resize', schedule); media.removeEventListener('change', schedule); };
  }, []);
  return { ref, progress };
}
function Navigation() {
  const [open, setOpen] = useState(false);
  return <header className="site-header"><a className="wordmark" href="#home" aria-label="Money Saving System home"><ChartNoAxesColumnIncreasing aria-hidden="true"/><span>MONEY SAVING<small>THE SYSTEM</small></span></a><nav aria-label="Main navigation" className={open ? 'navigation is-open' : 'navigation'}>{[['The story', '#home'], ['How it works', '#demo'], ['What’s inside', '#inside'], ['FAQs', '#questions']].map(([name, href]) => <a key={href} href={href} onClick={() => setOpen(false)}>{name}</a>)}</nav><a className="nav-explore" href="#system">Explore the system <ArrowUpRight size={15}/></a><button className="menu-toggle" aria-label={open ? 'Close navigation' : 'Open navigation'} aria-expanded={open} onClick={() => setOpen(!open)}>{open ? <X/> : <Menu/>}</button></header>;
}
function OpeningStory() {
  const { ref, progress } = useSceneProgress();
  const icons = [Home, Utensils, ShoppingBag, Car, Smartphone];
  return <><section className="salary-scene" id="home" aria-labelledby="salary-heading"><img className="scene-photo" src={`${asset}salary.webp`} srcSet={`${asset}salary-768.webp 768w, ${asset}salary.webp 1536w`} sizes="(max-width: 700px) 100vw, 100vw" alt="A young Indian professional checking his phone at home on salary day" width="1536" height="1024" fetchPriority="high"/><div className="scene-shade"/><div className="hero-copy"><Marker>01 / THE MONTH BEGINS</Marker><h1 id="salary-heading">Salary<br/><em>day.</em></h1><p>New month. New plans.<br/><span>“This month, I’ll save.”</span></p></div><div className="salary-notification"><span className="notification-check"><Check size={18}/></span><div><small>SALARY CREDITED</small><strong>+ ₹50,000</strong><span>A fresh start.</span></div></div><div className="hero-bottom"><a href="#expenses"><span className="scroll-circle"><ArrowDown size={17}/></span> Scroll to continue</a><span>A familiar month.<br/>A different possibility.</span><small>AN ILLUSTRATIVE STORY</small></div><div className="vertical-caption" aria-hidden="true">INTENTION IS ONLY THE BEGINNING</div></section>
  <section className="expense-scroll" id="expenses" ref={ref} aria-labelledby="expense-heading" style={{ '--story-progress': progress } as CSSProperties}><div className="expense-sticky"><div className="expense-text"><Marker>02 / EXPENSES TAKE OVER</Marker><h2 id="expense-heading">Life<br/><em>happens.</em></h2><p>One by one,<br/>the expenses start coming in.</p><span className="muted tiny">Ordinary life. Real commitments.</span></div><div className="expense-ledger"><div className="balance"><span>THIS MONTH’S BALANCE</span><strong aria-hidden="true">{inr(storyBalance(progress))}</strong><span className="sr-only">₹50,000 income, less ₹44,700 expenses, leaves ₹5,300.</span><small>₹50,000 salary · illustrative example</small></div><div className="expense-rows">{EXPENSES.map((item, i) => { const Icon = icons[i]; const reveal = Math.min(1, Math.max(0, progress * 5 - i)); return <div key={item.name} className={`expense-row ${reveal > 0 ? 'expense-active' : ''}`} style={{ '--reveal': reveal } as CSSProperties}><Icon size={21} strokeWidth={1.2}/><div><span>{item.name}</span><small>{item.note}</small></div><strong>−{inr(item.amount)}</strong><span className="expense-rule"/></div>; })}</div><div className="balance-track"><span style={{ width: `${storyBalance(progress) / 500}%` }}/></div><p className="tiny muted">Scroll to follow the month <ArrowDown size={12}/></p></div></div></section>
  <section className="month-end"><img className="scene-photo" src={`${asset}reflection.webp`} srcSet={`${asset}reflection-768.webp 768w, ${asset}reflection.webp 1536w`} sizes="(max-width: 700px) 100vw, 100vw" alt="The same professional reflecting on his expenses at the end of the month" loading="lazy" width="1536" height="1024"/><div className="scene-shade"/><div className="end-copy"><Marker>03 / DAY 30</Marker><h2>₹5,300<br/><em>left.</em></h2><p>The salary came.<br/>The expenses happened.<br/>The saving plan never did.</p><p className="muted">No clear savings. No progress to see.<br/>Same promise for next month.</p></div><div className="turning-point"><span>Maybe the problem isn’t your intention.</span><h3>Maybe you need <em>a system.</em></h3></div></section></>;
}
function QuoteOne() {
  return <aside className="quote-one section-shell"><figure><img src={`${asset}franklin.jpg`} alt="Historical portrait of Benjamin Franklin" width="380" height="460" loading="lazy"/><figcaption><a href="https://www.loc.gov/pictures/item/90709839/" target="_blank" rel="noreferrer">Portrait: Library of Congress ↗</a></figcaption></figure><div><Marker>A MOMENT OF PERSPECTIVE</Marker><blockquote>“Beware of little expenses;<br/>a small leak will sink<br/><em>a great ship.</em>”</blockquote><p className="quote-author">Benjamin Franklin <span>· The Way to Wealth</span></p><a className="source-link" href="https://www.gutenberg.org/files/40236/40236-h/40236-h.htm" target="_blank" rel="noreferrer">Read the source <ArrowUpRight size={12}/></a><p className="quote-disclaimer">For inspiration. No endorsement or affiliation with this product is implied.</p></div></aside>;
}
function GoalBreakdown() {
  const { ref, progress } = useSceneProgress();
  return <section className="goal-scroll ivory" ref={ref} id="how-it-works" style={{ '--goal-progress': progress } as CSSProperties}><div className="goal-sticky section-shell"><div><Marker>04 / A DIFFERENT WAY</Marker><h2>A big goal.<br/><em>A simple step.</em></h2><p>The goal may feel distant.<br/>You only need to focus on the next step.</p><p className="tiny muted">Illustration: ₹1,00,000 ÷ 98 days.<br/>Your own plan starts with your own numbers.</p></div><div className="goal-equation"><span>YOUR GOAL</span><strong className="big-goal">₹1,00,000</strong><div className="equation-line"><ArrowDown size={20}/><span>98 DAYS</span><ArrowDown size={20}/></div><div className="daily-step"><span>TODAY’S STEP</span><strong>₹1,020.41</strong><small>One day. One intentional step.</small></div></div></div></section>;
}
function ProductReveal({ preview }: { preview: (index: number) => void }) {
  return <section id="system" className="product-reveal section-shell"><div className="reveal-heading"><div><Marker>05 / INTRODUCING</Marker><h2>The Money<br/><em>Saving System.</em></h2></div><div><p>A practical system to help you plan,<br/>record and understand your savings progress.</p><a className="text-link" href="#demo">See how it works <ArrowDown size={16}/></a></div></div><div className="dashboard-stage"><div className="dashboard-notes">{[['YOUR GOAL','₹1,00,000'],['SAVED','₹28,571'],['REMAINING','₹71,429'],['DAILY TARGET','₹1,020'],['PROGRESS','28.6%']].map(([label, value]) => <span key={label}>{label}<strong>{value}</strong></span>)}</div><button className="laptop" onClick={() => preview(1)} aria-label="Expand the real Excel dashboard preview"><span className="laptop-camera"/><img src={`${asset}dashboard.webp`} alt="Actual uploaded Savings Goal Tracker dashboard with daily plan, carry forward and savings charts" width="1536" height="1024" loading="lazy"/><span className="expand-label"><Expand size={14}/> View real dashboard</span></button><div className="laptop-base"/></div><p className="product-caption">YOUR ACTUAL TRACKER. YOUR OWN GOALS.<span>Preview figures are illustrative; display annotations are rounded.</span></p></section>;
}
function SavingsDemo() {
  const [goal, setGoal] = useState('100000'); const [saved, setSaved] = useState('10000'); const [today, setToday] = useState(''); const [date, setDate] = useState(''); const [actual, setActual] = useState('600'); const [recorded, setRecorded] = useState<number | null>(null);
  useEffect(() => { const now = new Date(); setToday(dateKey(now)); const end = new Date(now); end.setDate(end.getDate() + 89); setDate(dateKey(end)); }, []);
  const plan = today ? calculateSavings(goal.trim() ? Number(goal) : NaN, saved.trim() ? Number(saved) : NaN, date, today) : null;
  const carry = recorded === null ? null : carryForward(1000, recorded);
  return <section className="demo-section section-shell" id="demo"><div className="demo-intro"><Marker>06 / TRY IT FOR YOURSELF</Marker><h2>See your plan<br/><em>in action.</em></h2><p>A little clarity goes a long way.<br/>Start with a goal that matters to you.</p><span className="demo-label">INTERACTIVE PREVIEW · NO SIGN-UP</span></div><div className="demo-workspace"><div className="demo-fields"><label htmlFor="demo-goal">Your goal <span>₹</span><input id="demo-goal" type="number" min="1" max="10000000000" value={goal} onChange={e => setGoal(e.target.value)}/></label><label htmlFor="demo-saved">Already saved <span>₹</span><input id="demo-saved" type="number" min="0" value={saved} onChange={e => setSaved(e.target.value)}/></label><label htmlFor="demo-date">Target date<input id="demo-date" type="date" min={today} value={date} onChange={e => setDate(e.target.value)}/></label></div><div className="demo-results" aria-live="polite">{plan && !plan.error ? <><div><span>REMAINING</span><strong>{inr(plan.remaining)}</strong></div><div><span>DAYS, INCLUDING TODAY</span><strong>{plan.days}</strong></div><div className="daily-result"><span>DAILY TARGET</span><strong>{inr(plan.daily, 2)}</strong></div><div className="demo-progress"><div style={{ '--progress': `${plan.progress}%` } as CSSProperties}><strong>{plan.progress.toFixed(1)}%</strong></div><span>{plan.remaining === 0 ? 'Goal reached' : 'OF YOUR GOAL'}</span></div></> : <p className="demo-error">{plan?.error || 'Preparing your plan…'}</p>}</div><p className="tiny muted">Remaining goal ÷ calendar days, including today. Figures rounded to two decimals. This preview does not edit your Excel file or store your entries.</p><div className="carry-demo"><div><Marker>WHEN LIFE DOESN’T GO TO PLAN</Marker><h3>Saved a little less?<br/><em>Keep going.</em></h3><p>Try a separate example with a ₹1,000 base daily target.</p></div><form onSubmit={e => { e.preventDefault(); if (actual.trim() && Number.isFinite(Number(actual)) && Number(actual) >= 0) setRecorded(Number(actual)); }}><label htmlFor="demo-actual">Today I saved (₹)<input id="demo-actual" required type="number" min="0" max="10000000000" step="0.01" value={actual} onChange={e => { setActual(e.target.value); setRecorded(null); }}/></label><button className="brass-button" type="submit">Record in preview <ArrowRight size={16}/></button></form></div><div className={`carry-flow ${carry ? 'recorded' : ''}`} aria-live="polite">{carry && recorded !== null ? <><span><small>RECORDED</small><strong>{inr(recorded, 2)}</strong></span><ArrowRight/><span><small>CARRY FORWARD</small><strong>{inr(carry.unpaid, 2)}</strong></span><ArrowRight/><span><small>NEXT REQUIREMENT</small><strong>{inr(carry.next, 2)}</strong><small>₹1,000 base + {inr(carry.unpaid, 2)}</small></span></> : <p>Your unpaid amount stays visible. Record an amount to see it move into the next requirement.</p>}</div></div></section>;
}
function ProgressStory() {
  const ref = useRef<HTMLElement>(null); const [visible, setVisible] = useState(false);
  useEffect(() => { const observer = new IntersectionObserver(([entry]) => { if (entry.isIntersecting) { setVisible(true); observer.disconnect(); } }, { threshold: 0.2 }); if (ref.current) observer.observe(ref.current); return () => observer.disconnect(); }, []);
  return <section ref={ref} className={`progress-story ${visible ? 'is-visible' : ''}`}><img className="scene-photo" src={`${asset}progress.webp`} srcSet={`${asset}progress-768.webp 768w, ${asset}progress.webp 1536w`} sizes="(max-width: 700px) 100vw, 100vw" alt="The same professional calmly working on his savings routine at his desk" width="1536" height="1024" loading="lazy"/><div className="scene-shade"/><div className="progress-copy"><Marker>07 / SMALL STEPS, REAL PROGRESS</Marker><h2>Progress<br/>becomes <em>visible.</em></h2><p>Not perfection.<br/>A system you can return to.</p></div><div className="progress-timeline">{[['DAY 1', '₹1,020'], ['DAY 7', '₹7,140'], ['DAY 15', '₹14,800'], ['DAY 30', '₹28,571']].map(([day, sum]) => <div key={day}><i/><small>{day}</small><strong>{sum}</strong></div>)}<span className="timeline-draw"/><p>Illustrative entries. Your savings depend on what you put aside.</p></div></section>;
}
function ProductCollection({ preview }: { preview: (index: number) => void }) {
  return <section id="inside" className="product-collection ivory section-shell"><div className="collection-heading"><div><Marker>08 / WHAT YOU’LL RECEIVE</Marker><h2>Three tools.<br/><em>One savings system.</em></h2></div><p>Motivation, a plan, and the guidance<br/>to put it into practice.</p></div><div className="collection-products">{products.map((product, index) => <article key={product.file} className={`product-item product-${product.file}`}><button className="product-image" onClick={() => preview(index)} aria-label={`View real preview: ${product.title}`}><img src={`${asset}${product.file}.webp`} width={index === 1 ? 1536 : 1800} height={index === 1 ? 1024 : 1200} alt={`Uploaded ${product.title} preview`} loading="lazy"/><span><Expand size={14}/> View real preview</span></button><Marker>{product.kind}</Marker><h3>{product.title}</h3><p className="product-purpose">{product.purpose}</p><p>{product.detail}</p></article>)}</div><div className="collection-promise"><Check size={18}/><span>WHAT YOU SEE IS WHAT YOU RECEIVE.</span><small>Digital files. No physical items. Microsoft Excel is required for the tracker.</small></div></section>;
}
function Questions() {
  const faqs = [ ['I don’t have a printer.', 'Printing is optional. Use the Excel tracker digitally, and print challenge pages only if you want to.'], ['I don’t know Excel.', 'The included User Guide explains setup, the dashboard and the daily workflow. You will need Microsoft Excel to use the workbook.'], ['I can’t save the same amount every day.', 'Record what you actually saved. The tracker keeps the unpaid requirement visible through its carry-forward logic.'], ['What if I miss a day?', 'Continue the plan. The carry-forward system keeps the unpaid requirement visible; you can return and record what you actually save.'], ['My goal isn’t ₹1 lakh.', 'Enter your own goal name, target amount, start date, target date and opening savings in the highlighted tracker fields.'], ['Is this a physical product?', 'No. This is a digital bundle: printable savings challenges, the Excel tracker and a step-by-step guide. The existing checkout provides a download link after purchase.'] ];
  return <section className="questions section-shell" id="questions"><div><Marker>A LITTLE CLARITY</Marker><h2>Made for<br/><em>real life.</em></h2><p>Some days won’t go to plan.<br/>That’s part of the plan.</p></div><div>{faqs.map(([q, a]) => <details key={q}><summary>{q}<ChevronDown size={18}/></summary><p>{a}</p></details>)}</div></section>;
}
function GoalsAndValue() {
  const goals = ['Emergency fund', 'Education', 'Laptop', 'Wedding', 'Travel', 'Car', 'Home', 'Hajj / Umrah']; const [selected, setSelected] = useState('Emergency fund');
  return <><aside className="quote-two section-shell"><Marker>MAKE ROOM FOR WHAT MATTERS</Marker><blockquote>“A man is rich in proportion to the number of things which he can afford to <em>let alone.</em>”</blockquote><div className="quote-two-source"><p>Henry David Thoreau <span>· Walden, “Where I Lived, and What I Lived For”</span></p><a className="source-link" href="https://www.gutenberg.org/files/205/205-h/205-h.htm" target="_blank" rel="noreferrer">Read the source <ArrowUpRight size={12}/></a></div><p className="quote-disclaimer">For inspiration. No endorsement or affiliation with this product is implied.</p></aside><section className="life-goals ivory section-shell"><Marker>09 / THE REASON BEHIND THE NUMBER</Marker><h2>Money isn’t the goal.<br/><em>What it makes possible is.</em></h2><div className="goals-editorial"><figure className="goal-photograph"><img src={`${asset}goals.webp`} srcSet={`${asset}goals-768.webp 768w, ${asset}goals.webp 1536w`} sizes="(max-width: 700px) 100vw, 100vw" width="1536" height="1024" alt="Everyday aspirations: learning, a home, travel and meaningful time with family" loading="lazy"/><figcaption>A little more choice. A little more breathing room.</figcaption></figure><div className="goal-selector"><h3>What are you<br/><em>saving for?</em></h3><div className="goal-options">{goals.map(goal => <button key={goal} aria-pressed={selected === goal} onClick={() => setSelected(goal)}>{goal}{selected === goal && <Check size={13}/>}</button>)}</div><p aria-live="polite">Your <strong>{selected.toLowerCase()}</strong> starts with a goal you can name.</p><a href="#demo" className="text-link">Try your numbers <ArrowUpRight size={15}/></a></div></div><p className="tiny muted">These are possible savings goals, not promised outcomes.</p></section><section className="value-section section-shell"><Marker>10 / MORE THAN A DOWNLOAD</Marker><h2>A reusable system.<br/><em>A clearer way forward.</em></h2><p>Give your savings goal a place to live.<br/>Return to it, record the real numbers, and see where you stand.</p><ol className="value-flow">{['Motivate', 'Plan', 'Save', 'Track', 'Adjust', 'See progress'].map((step, i) => <li key={step}><span>0{i + 1}</span>{step}{i < 5 && <ArrowRight size={15}/>}</li>)}</ol><div className="value-key"><span><strong>Challenges</strong> make progress tangible.</span><span><strong>The tracker</strong> brings the numbers together.</span><span><strong>The guide</strong> makes the next step clear.</span></div></section></>;
}
function FinalOffer() {
  const [price, setPrice] = useState<number | null>(null);
  useEffect(() => { const controller = new AbortController(); fetch('/api/admin/settings', { signal: controller.signal }).then(r => r.json()).then(data => { const value = Number(data.setting?.basePrice); if (data.success && Number.isFinite(value) && value > 0) setPrice(value); }).catch(() => {}); return () => controller.abort(); }, []);
  return <section className="final-offer section-shell" id="offer"><div><Marker>11 / YOUR NEXT CHAPTER</Marker><h2>The complete<br/><em>Money Saving System.</em></h2><p>Printable challenges + smart Excel tracker<br/>+ step-by-step user guide.</p><div className="offer-price">{price !== null ? <strong>{inr(price)}</strong> : <span>See current price at checkout</span>}<span>One-time digital purchase</span></div><a className="brass-button" href="#checkout-section">Begin my savings plan <ArrowRight size={18}/></a><div className="offer-trust"><span><ShieldCheck size={15}/> Razorpay checkout</span><span><Download size={15}/> Digital bundle</span></div></div><div className="offer-composition"><img className="offer-challenges" src={`${asset}challenges.webp`} alt="Included printable savings challenges" width="1800" height="1200" loading="lazy"/><img className="offer-guide" src={`${asset}guide.webp`} alt="Included step-by-step guide" width="1800" height="1200" loading="lazy"/><img className="offer-dashboard" src={`${asset}dashboard.webp`} alt="Included real savings dashboard" width="1536" height="1024" loading="lazy"/></div></section>;
}
function PreviewDialog({ index, close }: { index: number | null; close: () => void }) {
  const ref = useRef<HTMLDialogElement>(null);
  useEffect(() => { if (index === null) return; const previous = document.activeElement as HTMLElement; const overflow = document.body.style.overflow; ref.current?.showModal(); document.body.style.overflow = 'hidden'; return () => { ref.current?.close(); document.body.style.overflow = overflow; previous?.focus(); }; }, [index]);
  const product = index === null ? null : products[index];
  return <dialog ref={ref} className="preview-dialog" aria-label={product?.title || 'Product preview'} onCancel={close} onClick={e => { if (e.target === e.currentTarget) close(); }}>{product && <><header><span>{product.title} · Real product preview</span><button onClick={close} aria-label="Close preview"><X/></button></header><div className="preview-scroll"><img src={`${asset}${product.file}.png`} alt={`Full-size uploaded ${product.title}`}/></div><p>Preview image · Your purchase contains the digital product files.</p></>}</dialog>;
}
export default function SavingsStorefront() {
  const [preview, setPreview] = useState<number | null>(null);
  return <div className="savings-site"><VisitorTracker/><a href="#system" className="skip-link">Skip story and explore the product</a><Navigation/><main><OpeningStory/><QuoteOne/><GoalBreakdown/><ProductReveal preview={setPreview}/><SavingsDemo/><ProgressStory/><ProductCollection preview={setPreview}/><Questions/><GoalsAndValue/><FinalOffer/><div className="store-checkout"><CheckoutSection/></div><section className="honest-note"><span>A SMALL, HONEST NOTE</span><p>This system cannot save the money for you.<br/>It gives your savings a clearer place to plan, record and understand progress.</p></section></main><footer className="store-footer"><a href="#home" className="wordmark"><ChartNoAxesColumnIncreasing/><span>MONEY SAVING<small>THE SYSTEM</small></span></a><nav aria-label="Legal links"><a href="/terms">Terms</a><a href="/privacy">Privacy</a><a href="/refund">Refund policy</a><a href="/contact">Contact & support</a></nav><p>© {new Date().getFullYear()} Little Savings, Big Dreams.</p></footer><PreviewDialog index={preview} close={() => setPreview(null)}/></div>;
}
